apiVersion: v1
kind: Service
metadata:
  name: k6-loadtester
  namespace: flagger
spec:
  ports:
  - name: k6-loadtester-http-metrics
    port: 80
    targetPort: 80
  selector:
    name: k6-loadtester